# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Jan 09 16:28:52 2012
#      by: pyside-uic 0.2.13 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 392)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMouseTracking(True)
        MainWindow.setAcceptDrops(True)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 761, 352))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Desktop/git/grblfeedr/grblfeeder.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(180, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_2 = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(180, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.connectButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.connectButton.setMinimumSize(QtCore.QSize(0, 40))
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_4.addWidget(self.connectButton)
        self.disconnectButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.disconnectButton.setEnabled(False)
        self.disconnectButton.setMinimumSize(QtCore.QSize(0, 40))
        self.disconnectButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout_4.addWidget(self.disconnectButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.nextScreen = QtGui.QPushButton(self.verticalLayoutWidget)
        self.nextScreen.setObjectName("nextScreen")
        self.horizontalLayout_3.addWidget(self.nextScreen)
        self.exitButton2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.exitButton2.setObjectName("exitButton2")
        self.horizontalLayout_3.addWidget(self.exitButton2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(440, 20, 301, 281))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setAutoFillBackground(True)
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 731, 311))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.textEdit_2 = QtGui.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_2.setAcceptDrops(False)
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_4.addWidget(self.textEdit_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, 25, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalScrollBar = QtGui.QScrollBar(self.horizontalLayoutWidget)
        self.verticalScrollBar.setMinimumSize(QtCore.QSize(25, 0))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.verticalLayout_5.addWidget(self.verticalScrollBar)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.textEdit_3 = QtGui.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit_3.setAcceptDrops(False)
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_3.addWidget(self.textEdit_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.exitButton4 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.exitButton4.setObjectName("exitButton4")
        self.verticalLayout_2.addWidget(self.exitButton4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 741, 311))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.graphicsView = QtGui.QGraphicsView(self.horizontalLayoutWidget_2)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_7.addWidget(self.graphicsView)
        self.termWindow_2 = QtGui.QTextEdit(self.horizontalLayoutWidget_2)
        self.termWindow_2.setMaximumSize(QtCore.QSize(16777215, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.termWindow_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Terminal_Hex")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.termWindow_2.setFont(font)
        self.termWindow_2.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.termWindow_2.setMouseTracking(True)
        self.termWindow_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.termWindow_2.setAcceptDrops(False)
        self.termWindow_2.setFrameShadow(QtGui.QFrame.Plain)
        self.termWindow_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.termWindow_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.termWindow_2.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.termWindow_2.setReadOnly(True)
        self.termWindow_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.termWindow_2.setObjectName("termWindow_2")
        self.verticalLayout_7.addWidget(self.termWindow_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.go_g91 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_g91.setMinimumSize(QtCore.QSize(0, 40))
        self.go_g91.setObjectName("go_g91")
        self.verticalLayout_8.addWidget(self.go_g91)
        self.go_g90 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_g90.setObjectName("go_g90")
        self.verticalLayout_8.addWidget(self.go_g90)
        self.go_g00 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_g00.setMinimumSize(QtCore.QSize(0, 70))
        self.go_g00.setObjectName("go_g00")
        self.verticalLayout_8.addWidget(self.go_g00)
        self.go_g01 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_g01.setMinimumSize(QtCore.QSize(110, 70))
        self.go_g01.setObjectName("go_g01")
        self.verticalLayout_8.addWidget(self.go_g01)
        self.go_m03 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_m03.setObjectName("go_m03")
        self.verticalLayout_8.addWidget(self.go_m03)
        self.go_m05 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_m05.setObjectName("go_m05")
        self.verticalLayout_8.addWidget(self.go_m05)
        self.exitButton3 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.exitButton3.setObjectName("exitButton3")
        self.verticalLayout_8.addWidget(self.exitButton3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.go_m_x01 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_m_x01.sizePolicy().hasHeightForWidth())
        self.go_m_x01.setSizePolicy(sizePolicy)
        self.go_m_x01.setMinimumSize(QtCore.QSize(0, 40))
        self.go_m_x01.setObjectName("go_m_x01")
        self.horizontalLayout_7.addWidget(self.go_m_x01)
        self.go_p_x01 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_p_x01.setMinimumSize(QtCore.QSize(0, 40))
        self.go_p_x01.setObjectName("go_p_x01")
        self.horizontalLayout_7.addWidget(self.go_p_x01)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.go_m_x1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_m_x1.setObjectName("go_m_x1")
        self.horizontalLayout_8.addWidget(self.go_m_x1)
        self.go_m_x10 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_m_x10.setObjectName("go_m_x10")
        self.horizontalLayout_8.addWidget(self.go_m_x10)
        self.go_p_x1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_p_x1.setObjectName("go_p_x1")
        self.horizontalLayout_8.addWidget(self.go_p_x1)
        self.go_p_x10 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_p_x10.setObjectName("go_p_x10")
        self.horizontalLayout_8.addWidget(self.go_p_x10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.go_m_y01 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_m_y01.sizePolicy().hasHeightForWidth())
        self.go_m_y01.setSizePolicy(sizePolicy)
        self.go_m_y01.setMinimumSize(QtCore.QSize(0, 40))
        self.go_m_y01.setObjectName("go_m_y01")
        self.horizontalLayout_9.addWidget(self.go_m_y01)
        self.go_p_y01 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_p_y01.setMinimumSize(QtCore.QSize(0, 40))
        self.go_p_y01.setObjectName("go_p_y01")
        self.horizontalLayout_9.addWidget(self.go_p_y01)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.go_m_y1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_m_y1.setObjectName("go_m_y1")
        self.horizontalLayout_10.addWidget(self.go_m_y1)
        self.go_m_y10 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_m_y10.setObjectName("go_m_y10")
        self.horizontalLayout_10.addWidget(self.go_m_y10)
        self.go_p_y1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_p_y1.setObjectName("go_p_y1")
        self.horizontalLayout_10.addWidget(self.go_p_y1)
        self.go_p_y10 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_p_y10.setObjectName("go_p_y10")
        self.horizontalLayout_10.addWidget(self.go_p_y10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.go_m_z01 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_m_z01.sizePolicy().hasHeightForWidth())
        self.go_m_z01.setSizePolicy(sizePolicy)
        self.go_m_z01.setMinimumSize(QtCore.QSize(0, 40))
        self.go_m_z01.setObjectName("go_m_z01")
        self.horizontalLayout_12.addWidget(self.go_m_z01)
        self.go_p_z01 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_p_z01.setMinimumSize(QtCore.QSize(0, 40))
        self.go_p_z01.setObjectName("go_p_z01")
        self.horizontalLayout_12.addWidget(self.go_p_z01)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.go_m_z1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_m_z1.setObjectName("go_m_z1")
        self.horizontalLayout_11.addWidget(self.go_m_z1)
        self.go_m_z5 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_m_z5.setObjectName("go_m_z5")
        self.horizontalLayout_11.addWidget(self.go_m_z5)
        self.go_p_z1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_p_z1.setObjectName("go_p_z1")
        self.horizontalLayout_11.addWidget(self.go_p_z1)
        self.go_p_z5 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.go_p_z5.setObjectName("go_p_z5")
        self.horizontalLayout_11.addWidget(self.go_p_z5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setGeometry(QtCore.QRect(5, 6, 481, 310))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layout2 = QtGui.QWidget(self.splitter)
        self.layout2.setObjectName("layout2")
        self.topHoriz = QtGui.QHBoxLayout(self.layout2)
        self.topHoriz.setContentsMargins(5, 5, 5, 5)
        self.topHoriz.setContentsMargins(0, 0, 0, 0)
        self.topHoriz.setObjectName("topHoriz")
        self.termWindow = QtGui.QTextEdit(self.layout2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.termWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Terminal_Hex")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.termWindow.setFont(font)
        self.termWindow.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.termWindow.setMouseTracking(True)
        self.termWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.termWindow.setAcceptDrops(True)
        self.termWindow.setFrameShadow(QtGui.QFrame.Plain)
        self.termWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.termWindow.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.termWindow.setReadOnly(True)
        self.termWindow.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.termWindow.setObjectName("termWindow")
        self.topHoriz.addWidget(self.termWindow)
        self.controlVert = QtGui.QVBoxLayout()
        self.controlVert.setSpacing(5)
        self.controlVert.setContentsMargins(5, 5, 5, 5)
        self.controlVert.setObjectName("controlVert")
        self.loadButton = QtGui.QPushButton(self.layout2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loadButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.loadButton.setFlat(False)
        self.loadButton.setObjectName("loadButton")
        self.controlVert.addWidget(self.loadButton)
        self.sendOne = QtGui.QPushButton(self.layout2)
        self.sendOne.setFocusPolicy(QtCore.Qt.TabFocus)
        self.sendOne.setObjectName("sendOne")
        self.controlVert.addWidget(self.sendOne)
        self.sendCont = QtGui.QPushButton(self.layout2)
        self.sendCont.setMinimumSize(QtCore.QSize(90, 0))
        self.sendCont.setFocusPolicy(QtCore.Qt.TabFocus)
        self.sendCont.setObjectName("sendCont")
        self.controlVert.addWidget(self.sendCont)
        self.sendStop = QtGui.QPushButton(self.layout2)
        self.sendStop.setFocusPolicy(QtCore.Qt.TabFocus)
        self.sendStop.setFlat(False)
        self.sendStop.setObjectName("sendStop")
        self.controlVert.addWidget(self.sendStop)
        self.clearButton = QtGui.QPushButton(self.layout2)
        self.clearButton.setObjectName("clearButton")
        self.controlVert.addWidget(self.clearButton)
        self.clearTerm = QtGui.QPushButton(self.layout2)
        self.clearTerm.setObjectName("clearTerm")
        self.controlVert.addWidget(self.clearTerm)
        self.topHoriz.addLayout(self.controlVert)
        self.termLine = QtGui.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Terminal_Hex")
        font.setPointSize(10)
        self.termLine.setFont(font)
        self.termLine.setObjectName("termLine")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.bottomHoriz = QtGui.QHBoxLayout(self.layoutWidget)
        self.bottomHoriz.setContentsMargins(5, 5, 5, 5)
        self.bottomHoriz.setContentsMargins(0, 0, 0, 0)
        self.bottomHoriz.setObjectName("bottomHoriz")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottomHoriz.addItem(spacerItem)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Desktop/git/grblfeedr/grblfeeder.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.bottomHoriz.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottomHoriz.addItem(spacerItem1)
        self.exitButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(90, 0))
        self.exitButton.setMaximumSize(QtCore.QSize(100, 50))
        self.exitButton.setObjectName("exitButton")
        self.bottomHoriz.addWidget(self.exitButton)
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(495, 4, 250, 271))
        self.textEdit.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        self.currentProgress = QtGui.QProgressBar(self.tab)
        self.currentProgress.setGeometry(QtCore.QRect(495, 285, 251, 31))
        self.currentProgress.setProperty("value", 0)
        self.currentProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.currentProgress.setOrientation(QtCore.Qt.Horizontal)
        self.currentProgress.setObjectName("currentProgress")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 778, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuQt = QtGui.QMenu(self.menuBar)
        self.menuQt.setObjectName("menuQt")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLoad_GCode = QtGui.QAction(MainWindow)
        self.actionLoad_GCode.setEnabled(False)
        self.actionLoad_GCode.setObjectName("actionLoad_GCode")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.menuQt.addAction(self.actionConnect)
        self.menuQt.addAction(self.actionLoad_GCode)
        self.menuQt.addAction(self.actionExit)
        self.menuBar.addAction(self.menuQt.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "grblfeedr", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Serial Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Baud Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnectButton.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.nextScreen.setText(QtGui.QApplication.translate("MainWindow", "Next Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton2.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">grblfeeder</span><span style=\" font-family:\'sans-serif\'; font-size:11pt;\">, a GUI serial terminal for</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">sending commands to </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">GRBL</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:11pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">Uses </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">Python</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">, </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">PySide</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">, </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">Qt</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">, and </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">PySerial</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:11pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">Comments to </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">timkrins@gmail.com</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Processed", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton4.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Pre-Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.termWindow_2.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Terminal_Hex\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">termWindow</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.go_g91.setText(QtGui.QApplication.translate("MainWindow", "Relative (G91)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_g90.setText(QtGui.QApplication.translate("MainWindow", "Absolute (G90)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_g00.setText(QtGui.QApplication.translate("MainWindow", "Fast Move (G00)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_g01.setText(QtGui.QApplication.translate("MainWindow", "Linear Move (G01)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m03.setText(QtGui.QApplication.translate("MainWindow", "Motor On (M03)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m05.setText(QtGui.QApplication.translate("MainWindow", "Motor Off (M05)", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton3.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m_x01.setText(QtGui.QApplication.translate("MainWindow", "X - 0.1 (Left)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_p_x01.setText(QtGui.QApplication.translate("MainWindow", "X + 0.1 (Right)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m_x1.setText(QtGui.QApplication.translate("MainWindow", "X - 1", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m_x10.setText(QtGui.QApplication.translate("MainWindow", "X - 10", None, QtGui.QApplication.UnicodeUTF8))
        self.go_p_x1.setText(QtGui.QApplication.translate("MainWindow", "X + 1", None, QtGui.QApplication.UnicodeUTF8))
        self.go_p_x10.setText(QtGui.QApplication.translate("MainWindow", "X + 10", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m_y01.setText(QtGui.QApplication.translate("MainWindow", "Y - 0.1 (Further)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_p_y01.setText(QtGui.QApplication.translate("MainWindow", "Y + 0.1 (Closer)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m_y1.setText(QtGui.QApplication.translate("MainWindow", "Y - 1", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m_y10.setText(QtGui.QApplication.translate("MainWindow", "Y - 10", None, QtGui.QApplication.UnicodeUTF8))
        self.go_p_y1.setText(QtGui.QApplication.translate("MainWindow", "Y + 1", None, QtGui.QApplication.UnicodeUTF8))
        self.go_p_y10.setText(QtGui.QApplication.translate("MainWindow", "Y + 10", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m_z01.setText(QtGui.QApplication.translate("MainWindow", "Z - 0.1 (Down)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_p_z01.setText(QtGui.QApplication.translate("MainWindow", "Z + 0.1 (Up)", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m_z1.setText(QtGui.QApplication.translate("MainWindow", "Z - 1", None, QtGui.QApplication.UnicodeUTF8))
        self.go_m_z5.setText(QtGui.QApplication.translate("MainWindow", "Z - 5", None, QtGui.QApplication.UnicodeUTF8))
        self.go_p_z1.setText(QtGui.QApplication.translate("MainWindow", "Z + 1", None, QtGui.QApplication.UnicodeUTF8))
        self.go_p_z5.setText(QtGui.QApplication.translate("MainWindow", "Z + 5", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Direct Control", None, QtGui.QApplication.UnicodeUTF8))
        self.termWindow.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Terminal_Hex\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">termWindow</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("MainWindow", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.sendOne.setText(QtGui.QApplication.translate("MainWindow", "Send One Line", None, QtGui.QApplication.UnicodeUTF8))
        self.sendCont.setText(QtGui.QApplication.translate("MainWindow", "Send Continous", None, QtGui.QApplication.UnicodeUTF8))
        self.sendStop.setText(QtGui.QApplication.translate("MainWindow", "Stop Sending", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.clearTerm.setText(QtGui.QApplication.translate("MainWindow", "Clear Terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.termLine.setText(QtGui.QApplication.translate("MainWindow", "Enter Command", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.currentProgress.setFormat(QtGui.QApplication.translate("MainWindow", "Queue Progress: %p%", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Feeder", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQt.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_GCode.setText(QtGui.QApplication.translate("MainWindow", "Load GCode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))

