# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Sep 23 08:46:45 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 305)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMouseTracking(True)
        MainWindow.setAcceptDrops(True)
        MainWindow.setWindowOpacity(0.95)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 481, 251))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.topHoriz = QtGui.QHBoxLayout(self.layoutWidget)
        self.topHoriz.setContentsMargins(0, 0, 0, 0)
        self.topHoriz.setObjectName("topHoriz")
        self.termWindow = QtGui.QTextEdit(self.layoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.termWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Terminal_Hex")
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.termWindow.setFont(font)
        self.termWindow.setProperty("cursor", QtCore.Qt.BlankCursor)
        self.termWindow.setMouseTracking(True)
        self.termWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.termWindow.setAcceptDrops(True)
        self.termWindow.setFrameShadow(QtGui.QFrame.Plain)
        self.termWindow.setReadOnly(True)
        self.termWindow.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.termWindow.setObjectName("termWindow")
        self.topHoriz.addWidget(self.termWindow)
        self.controlVert = QtGui.QVBoxLayout()
        self.controlVert.setObjectName("controlVert")
        self.loadButton = QtGui.QPushButton(self.layoutWidget)
        self.loadButton.setMinimumSize(QtCore.QSize(0, 50))
        self.loadButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.loadButton.setFlat(False)
        self.loadButton.setObjectName("loadButton")
        self.controlVert.addWidget(self.loadButton)
        self.sendOne = QtGui.QPushButton(self.layoutWidget)
        self.sendOne.setFocusPolicy(QtCore.Qt.TabFocus)
        self.sendOne.setObjectName("sendOne")
        self.controlVert.addWidget(self.sendOne)
        self.sendCont = QtGui.QPushButton(self.layoutWidget)
        self.sendCont.setMinimumSize(QtCore.QSize(90, 0))
        self.sendCont.setFocusPolicy(QtCore.Qt.TabFocus)
        self.sendCont.setObjectName("sendCont")
        self.controlVert.addWidget(self.sendCont)
        self.sendStop = QtGui.QPushButton(self.layoutWidget)
        self.sendStop.setFocusPolicy(QtCore.Qt.TabFocus)
        self.sendStop.setObjectName("sendStop")
        self.controlVert.addWidget(self.sendStop)
        self.topHoriz.addLayout(self.controlVert)
        self.termLine = QtGui.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Terminal_Hex")
        font.setPointSize(10)
        self.termLine.setFont(font)
        self.termLine.setObjectName("termLine")
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.bottomHoriz = QtGui.QHBoxLayout(self.layoutWidget1)
        self.bottomHoriz.setContentsMargins(0, 0, 0, 0)
        self.bottomHoriz.setObjectName("bottomHoriz")
        self.appTitle = QtGui.QLabel(self.layoutWidget1)
        self.appTitle.setScaledContents(False)
        self.appTitle.setObjectName("appTitle")
        self.bottomHoriz.addWidget(self.appTitle)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottomHoriz.addItem(spacerItem)
        self.exitButton = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(50, 0))
        self.exitButton.setObjectName("exitButton")
        self.bottomHoriz.addWidget(self.exitButton)
        self.textEdit = QtGui.QTextEdit(self.centralWidget)
        self.textEdit.setGeometry(QtCore.QRect(500, 10, 251, 251))
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuQt = QtGui.QMenu(self.menuBar)
        self.menuQt.setObjectName("menuQt")
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad_GCode = QtGui.QAction(MainWindow)
        self.actionLoad_GCode.setObjectName("actionLoad_GCode")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuQt.addAction(self.actionLoad_GCode)
        self.menuQt.addAction(self.actionExit)
        self.menuBar.addAction(self.menuQt.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "qtSerialFeeder", None, QtGui.QApplication.UnicodeUTF8))
        self.termWindow.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Terminal_Hex\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Testing</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("MainWindow", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.sendOne.setText(QtGui.QApplication.translate("MainWindow", "Send One Line", None, QtGui.QApplication.UnicodeUTF8))
        self.sendCont.setText(QtGui.QApplication.translate("MainWindow", "Send Continous", None, QtGui.QApplication.UnicodeUTF8))
        self.sendStop.setText(QtGui.QApplication.translate("MainWindow", "Stop Sending", None, QtGui.QApplication.UnicodeUTF8))
        self.termLine.setText(QtGui.QApplication.translate("MainWindow", "Enter Command", None, QtGui.QApplication.UnicodeUTF8))
        self.appTitle.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; vertical-align:super;\">qt</span><span style=\" font-size:22pt;\">SerialFeeder</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuQt.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_GCode.setText(QtGui.QApplication.translate("MainWindow", "Load GCode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

